---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP   #  client's first request will determine which Pod will be used for all subsequent connections
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
